name: Deploy Backend

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Inject GitHub Secrets as Environment Variables
        run: |
          echo "AUTH0_CLIENT_ID=${{ secrets.AUTH0_CLIENT_ID }}" >> $GITHUB_ENV
          echo "AUTH0_DOMAIN=${{ secrets.AUTH0_DOMAIN }}" >> $GITHUB_ENV
          echo "AUTH0_REDIRECT_URI=${{ secrets.AUTH0_REDIRECT_URI }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm install

      - name: Start the backend
        run: node backend.js
